from typing import TypedDict
from enum import StrEnum

from src.graphs.researcher import research_tool
from src.graphs.support import support_tool


class FunctionEnum(StrEnum):
    ANALYST = 'analyst'
    ACCOUNTANT = 'accountant'
    RESEARCHER = 'researcher'
    AUDITOR = 'auditor'
    COMPLIANCE = 'compliance'
    ADVISOR = 'advisor'
    SUPPORT = 'support'


class Function(TypedDict):
    name: FunctionEnum
    description: str
    use_case: list[str]


TAXQ_FUNCTIONS = {
    FunctionEnum.ANALYST: Function(
        name=FunctionEnum.ANALYST, 
        description="Performs data interpretation and high-level analysis to understand the user's financial or tax-related query.",
        use_case=[
            "Extract and summarize key insights from financial data or user queries.",
            "Break down tax queries into actionable steps for other tools.",
            "Generate reports or summaries for management or clients."
        ]
    ),

    FunctionEnum.ACCOUNTANT: Function(
        name=FunctionEnum.ACCOUNTANT, 
        description="Handles financial record keeping, tax computation, and reporting in accordance with Nigerian accounting standards.",
        use_case=[
            "Prepare financial statements for SMEs or companies.",
            "Compute PAYE, VAT, and corporate tax liabilities.",
            "Assist with bookkeeping and account reconciliation tasks."
        ]
    ),

    FunctionEnum.RESEARCHER: Function(
        name=FunctionEnum.RESEARCHER, 
        description="Finds and interprets the latest laws, regulations, or financial data relevant to the user's request.",
        use_case=[
            "Retrieve information about new Nigerian tax reforms or government policies.",
            "Compare historical tax data or policy impacts.",
            "Support the Compliance or Analyst tool with up-to-date contextual knowledge."
        ]
    ),

    FunctionEnum.AUDITOR: Function(
        name=FunctionEnum.AUDITOR, 
        description="Verifies the accuracy, compliance, and integrity of financial or tax information across the workflow.",
        use_case=[
            "Review reports generated by the Financial Accountant for errors or inconsistencies.",
            "Ensure accounting entries comply with IFRS and FIRS regulations.",
            "Validate calculations or datasets before submission to external authorities."
        ]
    ),

    FunctionEnum.COMPLIANCE: Function(
        name=FunctionEnum.COMPLIANCE, 
        description="Ensures all processes, filings, and calculations adhere to relevant Nigerian laws and tax regulations.",
        use_case=[
            "Check if a user's query falls within Nigerian tax compliance boundaries.",
            "Validate that financial outputs align with FIRS and CAC rules.",
            "Monitor for red flags or anomalies that may require audit or review.",
            "Research on tax laws"
        ]
    ),

    FunctionEnum.ADVISOR: Function(
        name=FunctionEnum.ADVISOR, 
        description="Provides strategic insights and recommendations based on financial and compliance data.",
        use_case=[
            "Suggest tax-saving strategies or regulatory optimizations.",
            "Summarize business health from audit and analysis outputs.",
            "Notify users of potential risks or improvement opportunities."
        ]
    ),

    FunctionEnum.SUPPORT: Function(
        name=FunctionEnum.SUPPORT,
        description="Handles user inquiries, greetings, troubleshooting, and general assistance across financial, technical, and compliance-related interactions.",
        use_case=[
            "Respond to greetings, welcome messages, and introductory queries in a friendly and context-aware manner.",
            "Resolve user complaints or confusion regarding account activity, transactions, or platform features.",
            "Provide clear guidance on navigating tools, dashboards, simulations, or audit outputs.",
            "Assist with verification, onboarding, or status checks on pending tasks or requests.",
            "Escalate complex or domain-specific issues to specialized functions while ensuring continuity and clarity."
        ]
    )
}


TAXQ_TOOLS = {
    FunctionEnum.RESEARCHER: research_tool,
    FunctionEnum.SUPPORT: support_tool
}