version: "3.8"

services:
  mongodb:
    image: mongo:7
    container_name: mongodb
    restart: always
    command: mongod --quiet --logpath /dev/null
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - mongo_data:/data/db
    networks:
      - moneyhound_network

  redis:
    image: redis:7.2.4-alpine
    container_name: redis
    restart: always
    command: ["redis-server", "--appendonly", "yes", "--loglevel", "warning"]
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - redis_data:/data
    networks:
      - moneyhound_network

  rabbit:
    image: rabbitmq:3-management
    container_name: rabbit
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbit_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    networks:
      - moneyhound_network

volumes:
  mongo_data:
  redis_data:
  rabbit_data:
  api_data:

networks:
  moneyhound_network:
    driver: bridge